Coffee/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('menu/', include('menu.urls')),
    path('admin/', admin.site.urls),
]

menu/urls.py
from django.urls import path
from . import views

# namespace for menu
app_name = 'menu'
urlpatterns = [
	# /menu/
	path('', views.allitems, name='allitems'),

	# /menu/drink/5/
	path('drink/<int:drink_id>/', views.drinkdetail, name='drinkdetail'),

	# /menu/snack/2/
	path('snack/<int:snack_id>/', views.snackdetail, name='snackdetail'),

	# /menu/add/
	path('add/', views.additem, name='additem'),

	# /menu/edit/
	path('edit/', views.edititem, name='edititem'),

	# /menu/delete/
	path('delete/', views.deleteitem, name='deleteitem'),
]

menu/models.py
from django.db import models

# Create your models here.

#######################################################################3


# Menu items have a name, and a toString() method
class MenuItem(models.Model):
	item = models.CharField(max_length=10)
	def __str__(self):
		return self.item

# Drinks are menu items, and have reccommended snack pairs
class Drink(MenuItem):
	drink_name = models.CharField(max_length=75)
	#reccomend = models.ManyToManyField('Snack')
	def __str__(self):
		return self.drink_name

# Snacks are menu items, and have reccommended drink pairs
class Snack(MenuItem):
	snack_name = models.CharField(max_length=75)
	reccomend = models.ManyToManyField(Drink)
	def __str__(self):
		return self.snack_name


#########################################################################


# multiple Ingredients can be in any Menu Item
class Ingredient(models.Model):
	ingred_name = models.CharField(max_length=75)
	ingredients = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
	def __str__(self):
		return self.ingred_name

menu/forms.py
from django import forms

class addForm(forms.Form):
	Item_Name = forms.CharField()
	Snack_or_Drink = forms.CharField()
	Number_of_Ingredients = forms.IntegerField()

class deleteForm(forms.Form):
	Snack_or_Drink = forms.CharField()
	Item_Name = forms.CharField()

class ingredForm(forms.Form):
	Ingredient = forms.CharField()

menu/views.py
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404, render
from .models import Drink, Snack
from .forms import addForm, deleteForm

# Create your views here.

# /menu/
def allitems(request):
	drink_menu = Drink.objects.order_by('drink_name')[:len(Drink.objects.all())]
	snack_menu = Snack.objects.order_by('snack_name')[:len(Snack.objects.all())]
	context = {'drink_menu': drink_menu, 'snack_menu': snack_menu}
	return render(request, 'menu/allitems.html', context)

#################################################################

# /menu/snack/2/
def snackdetail(request, snack_id):
	current_snack = get_object_or_404(Snack, pk=snack_id)
	context = {'current_snack': current_snack}
	return render(request, 'menu/snackdetail.html', context)

# /menu/drink/5/
def drinkdetail(request, drink_id):
	current_drink = get_object_or_404(Drink, pk=drink_id)
	context = {'current_drink': current_drink}
	return render(request, 'menu/drinkdetail.html', context)

#################################################################

# /menu/add/
def additem(request):
	form = addForm()
	return render(request, 'menu/add.html', {'form': form})

def postadd(request):
	form = addForm(request.POST)
	form2 = ingredForm()
	if form.is_valid():
		num_i = form.cleaned_data['Number_of_Ingredients']
		Item_Name = form.cleaned_data['Item_Name']
		s_or_d = form.cleaned_data['Snack_or_Drink']
	context = {'num_i': num_i, 'Item_Name': Item_Name, 's_or_d': s_or_d, 'form2': form2}
	render(request, 'menu/add.html', context)

###################################################################

# /menu/edit/
def edititem(request):
	form1 = deleteForm()
	form2 = addForm()
	return render(request, 'menu/edit.html', {'form1': form1, 'form2': form2})

###################################################################


# /menu/delete/
def deleteitem(request):
	form = deleteForm()
	return render(request, 'menu/delete.html', {'form': form})

menu/templates/menu/add.html

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'menu/style.css' %}">

<h1>Add Menu Item</h1>

<div class="container">
	<form method="postadd">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Next</button>
	</form>
</div>

<h2>{{ num_i }}</h2>

{% if num_i > 0 %}
	<form method="POST">
		{% csrf_token %}
		{% for i in num_i %}
			{{ form2.as_p }}
		{% endfor %}
		<button type="submit">Next</button>
	</form>
{% else %}
	<p>Invalid number of Ingredients.</p>
{% endif %}

<p style="text-indent: 300px"><a href="{% url 'menu:allitems' %}">{{ "Back to Menu" }}</a></p>

menu/templates/menu/allitems.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'menu/style.css' %}">

<style>
* {
  box-sizing: border-box;
}

/* Create three equal columns that floats next to each other */
.column {
  float: left;
  width: 33.33%;
  padding: 10px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}
</style>

<div class="row">

	<div class="column">
	<!--  menu  -->
		<h1>MENU</h1>

		<h2>Drinks</h2>
		{% if drink_menu %}
			<ul>
			{% for d in drink_menu %}
				<li><a href="{% url 'menu:drinkdetail' d.id %}">{{ d.drink_name }}</a></li>
			{% endfor %}
			</ul>
		{% else %}
			<p>No Drinks are on the Menu.</p>
		{% endif %}
	</div>
	<div class="column">
		<br><br><br><br><br><br><br>
		<h2>Snacks</h2>
		{% if snack_menu %}
			<ul>
			{% for s in snack_menu %}
				<li><a href="{% url 'menu:snackdetail' s.id %}">{{ s.snack_name }}</a></li>
			{% endfor %}
			</ul>
		{% else %}
			<p>No Snacks are on the Menu.</p>
		{% endif %}
	</div>

	<div class="column" style="background-color:#F4A460;">
	<!-- add/edit/delete a drink -->

		<h1 style="color: black">EDIT</h1>
		<li style="color: black"><a style="color: black" href="{% url 'menu:additem' %}">{{ "Add Menu Item" }}</a></li>
		<li style="color: black"><a style="color: black" href="{% url 'menu:edititem' %}">{{ "Edit Menu Item" }}</a></li>
		<li style="color: black"><a style="color: black" href="{% url 'menu:deleteitem' %}">{{ "Delete Menu Item" }}</a></li>
		<br><br><br><br><br>

	</div>
</div>

menu/templates/menu/delete.html

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'menu/style.css' %}">


<h1>Delete Menu Item</h1>
<h2>Enter Item to Delete:</h2>

<div class="container">
	<form method="deleteitem">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Delete</button>
	</form>
</div>

<p style="text-indent: 300px"><a href="{% url 'menu:allitems' %}">{{ "Back to Menu" }}</a></p>

menu/templates/menu/drinkdetail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'menu/style.css' %}">

<h1>{{ current_drink.drink_name }}</h1>
<h2>Ingredients</h2>
{% if current_drink.ingredient_set.all %}
	<ul>
	{% for i in current_drink.ingredient_set.all %}
		<li>{{ i.ingred_name }}</li>
	{% endfor %}
	</ul>
{% else %}
	<p>No ingredients added.</p>
{% endif %}
<h2>Reccomended Snack Pairs</h2>
{% if current_drink.snack_set.all %}
	<ul>
	{% for s in current_drink.snack_set.all %}
		<li>{{ s.snack_name }}</li>
	{% endfor %}
	</ul>
{% else %}
	<p>No recommended snack pairs.</p>
{% endif %}

<p style="text-indent: 300px"><a href="{% url 'menu:allitems' %}">{{ "Back to Menu" }}</a></p>

menu/templates/menu/edit.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'menu/style.css' %}">

<h1>Edit Menu Item</h1>

<!-- delete incorrect item -->


<div class="container">
	<form method="edititem">
		{% csrf_token %}
		<h2>Enter Item to Edit:</h2>
		{{ form1.as_p }}
		<h2>Enter Edited Info:</h2>
		{{ form2.as_p }}
		<button type="submit">Next</button>
	</form>
</div>

<p style="text-indent: 300px"><a href="{% url 'menu:allitems' %}">{{ "Back to Menu" }}</a></p>

menu/templates/menu/snackdetail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'menu/style.css' %}">

<h1>{{ current_snack.snack_name }}</h1>
<h2>Ingredients</h2>
{% if current_snack.ingredient_set.all %}
	<ul>
	{% for i in current_snack.ingredient_set.all %}
		<li>{{ i.ingred_name }}</li>
	{% endfor %}
	</ul>
{% else %}
	<p>No ingredients added.</p>
{% endif %}
<h2>Reccomended Drink Pairs</h2>
{% if current_snack.reccomend.all %}
	<ul>
	{% for d in current_snack.reccomend.all %}
		<li>{{ d.drink_name }}</li>
	{% endfor %}
	</ul>
{% else %}
	<p>No recommended drink pairs.</p>
{% endif %}

<p style="text-indent: 300px"><a href="{% url 'menu:allitems' %}">{{ "Back to Menu" }}</a></p>